name: canvas_query
version: 0.2.0-dev
author: Dennis Kaselow <Dennis.Kaselow+canvasquery@gmail.com>
description: A wrapper library for the HTML5 Canvas element which adds a lot of common use image manipulation methods mainly convenient for gamedevelopers.
homepage: https://github.com/denniskaselow/CanvasQuery.git
dependencies:
  browser: any
dev_dependencies:
  unittest: any